/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Tue, Apr 04, 2006                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :H8/3694F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.3.0).     */
/*                                                                     */
/***********************************************************************/
#pragma stacksize 0x200         /* Do not modify this line. */
