/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Tue, Nov 08, 2016                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :RX220                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#pragma stacksize si=0x600   /* Interrupt stack */
#pragma stacksize su=0x040   /* User stack (not used) */
