#include <lv2/macros.h.S>
#include <lv2/symbols.h>

#ifdef create_kernel_object_symbol
LV2_FUNCTION(create_kernel_object, create_kernel_object_symbol)
#endif

#ifdef destroy_kernel_object_symbol
LV2_FUNCTION(destroy_kernel_object, destroy_kernel_object_symbol)
#endif

#ifdef destroy_shared_kernel_object_symbol
LV2_FUNCTION(destroy_shared_kernel_object, destroy_shared_kernel_object_symbol)
#endif

#ifdef open_kernel_object_symbol
LV2_FUNCTION(open_kernel_object, open_kernel_object_symbol)
#endif

#ifdef open_shared_kernel_object_symbol
LV2_FUNCTION(open_shared_kernel_object, open_shared_kernel_object_symbol)
#endif

#ifdef close_kernel_object_handle_symbol
LV2_FUNCTION(close_kernel_object_handle, close_kernel_object_handle_symbol)
#endif






