/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Tue, Jan 25, 2011                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :RX62N                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.51).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#pragma stacksize si=0x1000	/* Interrupt stack */
#pragma stacksize su=0x0080	/* User stack (not used) */
