#!/bin/sh

## Configure the build.
cd ImageMagick
CFLAGS="-I$PSL1GHT/ppu/include -I$PS3DEV/portlibs/ppu/include" \
LDFLAGS="-L$PSL1GHT/ppu/lib -L$PS3DEV/portlibs/ppu/lib -lrt -llv2" \
PKG_CONFIG_PATH="$PS3DEV/portlibs/ppu/lib/pkgconfig" \
sh configure --host="ppu" --enable-static --disable-shared \
--disable-hdri \
--disable-largefile \
--disable-openmp \
--disable-docs \
--without-modules \
--without-magick-plus-plus \
--without-perl \
--with-frozenpaths \
--with-bzlib \
--with-autotrace \
--with-x \
--with-xml \
--with-zlib \
--with-quantum-depth=16 \
--with-djvu \
--with-dps \
--with-fftw \
--with-flif \
--with-fpx \
--with-fontconfig \
--with-freetype \
--with-gslib \
--with-gvc \
--with-jbig \
--with-lcms \
--with-lqr \
--with-lzma \
--with-openexr \
--with-openjp2 \
--with-pango \
--with-png \
--with-raqm \
--with-rsvg \
--with-tiff \
--with-webp \
--with-wmf \
|| { exit 1; }
cd ..
