#!/bin/sh

## Configure the build.
cd libtga
CFLAGS="-I$PSL1GHT/ppu/include -I$PS3DEV/portlibs/ppu/include"  \
LDFLAGS="-L$PSL1GHT/ppu/lib -L$PS3DEV/portlibs/ppu/lib -lrt -llv2" \
PKG_CONFIG_PATH="$PS3DEV/portlibs/ppu/lib/pkgconfig" \
cross_compiling=1 \
sh configure --host="powerpc64-ps3-elf" --enable-static --disable-shared  --prefix=$PS3DEV/portlibs/ppu --with-gnu-ld\
|| { exit 1; }
cd ..