/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Tue, Mar 30, 2010                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :SH7261                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
#pragma stacksize 0x8000        /* Do not modify this line. */
